# @package _global_

seed: 42
lr: 0.001
epochs: 10
logfreq: 10
batch_size: 32
num_threads: 1
backend: 'gloo'
hidden_size: 10


lightning: null

work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/data/

defaults:
  - _self_
  - comet: default
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

hydra:
  run:
    dir: "data/runs/${now:%Y-%m-%d_%H-%M-%S}"
  sweep:
    dir: "data/runs/${now:%Y-%m-%d_%H-%M-%S}"
    subdir: ${hydra.job.num}
  # job_logging:
  #   version: 1
  #   formatters:
  #     simple:
  #       format: '[%(name)s][%(levelname)s] - %(message)s'
  #     detailed:
  #       format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
  #   handlers:
  #     console:
  #       class: logging.StreamHandler
  #       formatter: simple
  #       level: DEBUG
  #       stream: ext://sys.stdout
  #     file:
  #       class : logging.handlers.RotatingFileHandler
  #       formatter: detailed
  #       level: DEBUG
  #       filename: training_debug.log
  #   root:
  #     handlers: [console, file]

  #   disable_existing_loggers: false
