setup:
    id: null
    group: null
    config: null
    # job_type: null
    save_code: true
    sync_tensorboard: true
    mode: online
    resume: allow
    entity: mlops
    project: mlops
    settings:
        start_method: thread
    # tags:
# watch:
#   log: all
#   # log_freq: 100


